// Yi.Vben5/apps/web-antd/src/views/workflow/processInstance/data.tsx
import type { FormSchemaGetter } from '#/adapter/form';
import type { VxeGridProps } from '#/adapter/vxe-table';

import { DictEnum } from '#/constants';

import { OptionsTag } from '#/components/table';
import { renderDict } from '#/utils/render';

import { activityStatusOptions } from '../processDefinition/constant';

export const querySchema: FormSchemaGetter = () => [
  {
    component: 'Input',
    label: '任务名称',
    fieldName: 'nodeName',
  },
  {
    component: 'Input',
    label: '流程名称',
    fieldName: 'flowName',
  },
  {
    component: 'Input',
    label: '流程编码',
    fieldName: 'flowCode',
  },
];

export const columns: VxeGridProps['columns'] = [
  { type: 'checkbox', width: 60 },
  {
    field: 'flowName',
    title: '流程名称',
    minWidth: 150,
  },
  {
    field: 'nodeName',
    title: '任务名称',
    minWidth: 150,
  },
  {
    field: 'flowCode',
    title: '流程编码',
    minWidth: 150,
  },
  {
    field: 'createByName',
    title: '申请人',
    minWidth: 150,
  },
  {
    field: 'version',
    title: '版本号',
    minWidth: 150,
    formatter: ({ cellValue }) => `V${cellValue}.0`,
  },
  {
    field: 'activityStatus',
    title: '状态',
    minWidth: 100,
    slots: {
      default: ({ row }) => {
        const cellValue = row.activityStatus;
        return (
          <OptionsTag
            options={activityStatusOptions as any}
            value={cellValue}
          />
        );
      },
    },
  },
  {
    field: 'flowStatus',
    title: '流程状态',
    minWidth: 100,
    slots: {
      default: ({ row }) => {
        return renderDict(row.flowStatus, DictEnum.WF_BUSINESS_STATUS);
      },
    },
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: '操作',
    resizable: false,
    width: 200,
  },
];

// Yi.Vben5/apps/web-antd/src/views/monitor/loginlog/data.tsx
import type { VNode } from 'vue';

import type { FormSchemaGetter } from '#/adapter/form';
import type { VxeGridProps } from '#/adapter/vxe-table';

import { renderBrowserIcon, renderOsIcon } from '#/utils/render';

export const querySchema: FormSchemaGetter = () => [
  {
    component: 'Input',
    fieldName: 'loginIp',
    label: 'IP地址',
  },
  {
    component: 'Input',
    fieldName: 'loginUser',
    label: '用户账号',
  },
  {
    component: 'RangePicker',
    fieldName: 'dateTime',
    label: '登录日期',
  },
];

export const columns: VxeGridProps['columns'] = [
  { type: 'checkbox', width: 60 },
  {
    title: '用户账号',
    field: 'loginUser',
  },
  {
    title: 'IP地址',
    field: 'loginIp',
  },
  {
    title: 'IP地点',
    field: 'loginLocation',
    width: 200,
  },
  {
    title: '浏览器',
    field: 'browser',
    slots: {
      default: ({ row }) => {
        return renderBrowserIcon(row.browser, true) as VNode;
      },
    },
  },
  {
    title: '系统',
    field: 'os',
    slots: {
      default: ({ row }) => {
        /**
         *  Windows 10 or Windows Server 2016 太长了 分割一下 详情依旧能看到详细的
         */
        let value = row.os;
        if (value) {
          const split = value.split(' or ');
          if (split.length === 2) {
            value = split[0];
          }
        }
        return renderOsIcon(value, true) as VNode;
      },
    },
  },
  {
    title: '信息',
    field: 'logMsg',
  },
  {
    title: '日期',
    field: 'creationTime',
  },
  {
    field: 'action',
    fixed: 'right',
    slots: { default: 'action' },
    title: '操作',
    width: 150,
  },
];
